### ISSUE TITLE
Inference results are different each run in mobile

### ISSUE THREAD

**Issue by HaMMeRSI** [Unity-Technologies/barracuda-release#73] opened 2020-07-13 16:55 UTC
Hey, I have noticed that my model is acting differently between pc and mobile.
I attached a tester that I have created to demonstrate the issue. 
If played in the editor the results are constant.
If played in oculus quest the results are different each run.
The model attached is not fully trained but good enough to show the issue.

[BarracudaTester.zip](https://github.com/Unity-Technologies/barracuda-release/files/4913899/BarracudaTester.zip)

**Comment by AlexRibard** [comment] 2020-07-13 17:01
What GPU backend are you using on mobile? Vulkan or OpenGL ES 3.1?
We have noticed some driver issues with OpenGL ES 3.1, so I would recommend to try Vulkan.
If that is not possible, is using a CPU worker ok? Maybe perf is reasonable given your small input size.

**Comment by HaMMeRSI** [comment] 2020-07-13 20:57
Interesting, seems like changing it to CSharpBurst stablized the results and works as expected in both platforms without any noticeable performance hit.
I am using OpenGL ES 3.1.

Are there any plans of fixing it soon? I do rather use the gpu still.

**Comment by AlexRibard** [comment] 2020-07-13 21:04
Yeah, your model is quite small, so I wouldn't have expected much perf diff.
The main problem is coming from driver support for OpenGLES. We have found it to be quite over the place depending on the platform. Venders also seem to prioritize Vulkan support.
So I would recommend switching to Vulkan backend.
@mantasp do you know the state of Vulkan on Oculus ?

**Comment by FlorentGuinier** [comment] 2021-04-29 11:27
Here are info about vulkan support of oculus in unity : https://developer.oculus.com/blog/vulkan-support-for-oculus-quest-in-unity-experimental/.

**Comment by FlorentGuinier** [comment] 2021-04-29 11:28
@HuMMeRSI closing the issue as it seems the problem is solved/explained, please reopen if you are still experiencing troubles.

**Closed as completed by FlorentGuinier** 2021-04-29 11:28 UTC
