### ISSUE TITLE
Running on CPU or Creating GPU Baked Worker takes almost 40 sec on Android

### ISSUE THREAD

**Issue by hajiarab1988** [Unity-Technologies/barracuda-release#118] opened 2020-12-04 17:00 UTC
Hi
I  want to run a simple code that includes Barracuda and it works fine in the editor but when I run the APK file on the phone two situations happens :

When I'm using CPU baked types like CSharpBurst, the process of worker creation takes about 1 sec but executing the model takes almost 40 seconds and makes the screen completely freeze.

When I use GPU baked types like ComputePrecompiled, worker creation takes more than 40 seconds but model execution takes almost 1 second.
Is it something normal? and could you please give me the best configuration for android devices in terms of Worker type, Executing, and Peek method?

Unity 2018.4.25 and Barracuda 1.2.0

@mantasp
@AlexRibard
here is [the model i use](https://github.com/Unity-Technologies/barracuda-release/files/5644026/QuickDraw2.zip) and my code:

            private string[] m_Labels = { "Apple", "Shovel", "Mushroom", "Clock", "Cloude", "Eye", "Sun", "Star", "Butterfly", "Circle" };
            private void Start()
        {
            model = ModelLoader.Load(modelSource);
            worker = WorkerFactory.CreateWorker(WorkerFactory.Type.ComputePrecompiled, model);
            InferenceTest(texture) ;
        }

           private Tensor InferenceTest(Texture2D input_texture2D)
        {
            Tensor tensor = new Tensor(input_texture2D,1);
            tensor.Print();
            worker.Execute(tensor);
            var output_nn = worker.Peek();
            int correct = -1;
            float prv = 0;
            for (int i = 0; i < 10; i++)
            {
                if (output_nn[0,0,0,i] > prv)
                {
                    prv = output_nn[0,0,0,i];
                    correct = i;
                }
            }
            Debug.Log(m_Labels[correct] + " is what i thik it is!");
            tensor.Dispose();
            output_nn.Dispose();
            worker?.Dispose();
            model = null;

            return output_nn;
        }
`

**Comment by AlexRibard** [comment] 2020-12-04 17:28
Judging on your model, it is indeed surprising that it goes that slow.
Out of curiosity what device are you using? And which version of barracuda?
Thanks!

**Comment by hajiarab1988** [comment] 2020-12-04 17:45
@AlexRibard Thanks for your fast response
So is there any problem with my code?
I'm using Barracuda 1.2.0 and the phone is a Samsung galaxy prime plus

**Comment by mantasp** [comment] 2020-12-04 18:35
@hajiarab1988 is your app running on Vulkan GFX API?

**Comment by hajiarab1988** [comment] 2020-12-04 18:53
@mantasp thanks for your response
No, it's not

My rendering configuration :
![image](https://user-images.githubusercontent.com/39706772/101202670-ce4f1300-367e-11eb-8168-17e0085bb051.png)

and if it gives any clue, I put **Graphic Emulation** on **No Emulation**

**Comment by hajiarab1988** [comment] 2020-12-05 06:05
@AlexRibard @mantasp On a Samsung Galaxy s7, 40 seconds decreased to 12!

**Comment by mantasp** [comment] 2020-12-05 08:13
@hajiarab1988 on Android our min spec is device that can run Vulkan GFX API. (You can force it by unchecking  "Auto Graphics API" and making Vulkan first in the list and removing GL ES from the list). Some networks might work on Open GL ES 3.1, but in general we don't support this graphics API for running Barracuda. I suspect that your first mentioned device is too old to run Vulkan and compute shader compilation takes much longer on Open GL ES than on Vulkan, and probably that's why you see such long startup times.
Though Galaxy S7 should be fine. Could you check if Galaxy S7 is starting in Vulkan? you can do it by checking first app logs when it's starting via `adb logcat -s Unity`.

**Comment by mantasp** [comment] 2020-12-09 16:12
I just tested simple project on Galaxy S8 and can confirm that slow initialization is caused by slow shader compilation on GLES 3.1+, which is fixed by switching to Vulkan graphics API.

**Closed as completed by mantasp** 2020-12-09 16:12 UTC
