### ISSUE TITLE
NotSupportedException: Format version not supported: 244

### ISSUE THREAD

**Issue by KamilMatejuk** [Unity-Technologies/barracuda-release#254] opened 2022-01-20 03:41 UTC
Hi.
I'm using Unity ML-Agent and successfully trained model, however when I try to load this model via script it returns an error.

**Versions:**
Model format: ONNX
OS: Ubuntu 20.04
ml-agents: 0.28.0,
ml-agents-envs: 0.28.0,
Communicator API: 1.5.0,
PyTorch: 1.8.1+cu102,
Connected to Unity environment with package version 2.0.1 and communication version 1.5.0

What is interesting is when I physically move model into model field in editor, it works. Only when I try to load it via script it crashes.

The path of model is `Assets/Resources/brain.onnx`

When loading with method from [here](https://github.com/Unity-Technologies/ml-agents/blob/0.14.1/Project/Assets/ML-Agents/Examples/SharedAssets/Scripts/ModelOverrider.cs#L98-L133):
```csharp
public static NNModel LoadModel1(string path) {
    byte[] model = null;
    try {
        model = File.ReadAllBytes(path);
    } catch (IOException) {
        Debug.Log($"Couldn't load file {path}");
        return null;
    }
    NNModel asset = ScriptableObject.CreateInstance<NNModel>();
    asset.modelData = ScriptableObject.CreateInstance<NNModelData>();
    asset.modelData.Value = model;
    string[] pathArr = path.Split('/');
    string name = pathArr[pathArr.Length - 1];
    asset.name = name.Split('.')[0];
    return asset;
}
```
it returns error:
```
NotSupportedException: Format version not supported: 244
Unity.Barracuda.ModelLoader.Load (System.IO.BinaryReader fileReader, System.Boolean verbose, System.Boolean applyPatching, System.Boolean skipWeights) (at Library/PackageCache/com.unity.barracuda@2.0.0/Barracuda/Runtime/Core/ModelLoader.cs:111)
Unity.Barracuda.ModelLoader.Load (System.Byte[] stream, System.Boolean verbose, System.Boolean skipWeights) (at Library/PackageCache/com.unity.barracuda@2.0.0/Barracuda/Runtime/Core/ModelLoader.cs:68)
Unity.Barracuda.ModelLoader.Load (Unity.Barracuda.NNModel model, System.Boolean verbose, System.Boolean skipWeights) (at Library/PackageCache/com.unity.barracuda@2.0.0/Barracuda/Runtime/Core/ModelLoader.cs:29)
Unity.MLAgents.Inference.ModelRunner..ctor (Unity.Barracuda.NNModel model, Unity.MLAgents.Actuators.ActionSpec actionSpec, Unity.MLAgents.Policies.InferenceDevice inferenceDevice, System.Int32 seed) (at Library/PackageCache/com.unity.ml-agents@2.0.1/Runtime/Inference/ModelRunner.cs:72)
Unity.MLAgents.Academy.GetOrCreateModelRunner (Unity.Barracuda.NNModel model, Unity.MLAgents.Actuators.ActionSpec actionSpec, Unity.MLAgents.Policies.InferenceDevice inferenceDevice) (at Library/PackageCache/com.unity.ml-agents@2.0.1/Runtime/Academy.cs:620)
Unity.MLAgents.Policies.BarracudaPolicy..ctor (Unity.MLAgents.Actuators.ActionSpec actionSpec, System.Collections.Generic.IList`1[T] actuators, Unity.Barracuda.NNModel model, Unity.MLAgents.Policies.InferenceDevice inferenceDevice, System.String behaviorName) (at Library/PackageCache/com.unity.ml-agents@2.0.1/Runtime/Policies/BarracudaPolicy.cs:84)
Unity.MLAgents.Policies.BehaviorParameters.GeneratePolicy (Unity.MLAgents.Actuators.ActionSpec actionSpec, Unity.MLAgents.Actuators.ActuatorManager actuatorManager) (at Library/PackageCache/com.unity.ml-agents@2.0.1/Runtime/Policies/BehaviorParameters.cs:240)
Unity.MLAgents.Agent.ReloadPolicy () (at Library/PackageCache/com.unity.ml-agents@2.0.1/Runtime/Agent.cs:651)
Unity.MLAgents.Policies.BehaviorParameters.UpdateAgentPolicy () (at Library/PackageCache/com.unity.ml-agents@2.0.1/Runtime/Policies/BehaviorParameters.cs:276)
Unity.MLAgents.Policies.BehaviorParameters.set_Model (Unity.Barracuda.NNModel value) (at Library/PackageCache/com.unity.ml-agents@2.0.1/Runtime/Policies/BehaviorParameters.cs:108)
Unity.MLAgents.Agent.SetModel (System.String behaviorName, Unity.Barracuda.NNModel model, Unity.MLAgents.Policies.InferenceDevice inferenceDevice) (at Library/PackageCache/com.unity.ml-agents@2.0.1/Runtime/Agent.cs:636)
CarAgent.Start () (at Assets/Player/CarAgent.cs:63)
```
I tried using method from [here](https://github.com/Unity-Technologies/barracuda-release/issues/76) as well:
```csharp
public static Model LoadModel2(string path) {
    return ModelLoader.Load((NNModel)Resources.Load(path));
}
```
but I need NNModel
```
cannot convert from 'Unity.Barracuda.Model' to 'Unity.Barracuda.NNModel'
```

**Comment by FlorentGuinier** [comment] 2022-01-24 10:31
Hi @KamilMatejuk 
`public static NNModel LoadModel1(string path) {`
Is expecting a serialize NNModel ressource aka a `.bc` asset. While you provide a .onnx file thus the problem.
Two possible solution here:

Import the onnx file in editor and serialize the NNModel as a .bc asset that you load using the code above.
Using `NNModel.modelData.Value` or alternatively `ModelWriter.Save(filename,...)`

Or
Use the `ONNXModelConverter.Convert(byte[] buffer)` method to convert from onnx file data directly to a Model.

I'm closing the question as i feel it was answered :) Please reopen if needed!

Have a great day!
Florent

**Closed by FlorentGuinier** 2022-01-24 10:31 UTC

**Comment by jhlee0918** [comment] 2022-02-21 06:01
@FlorentGuinier  Hello~ 
I have same problem. 

The model trained without problems.
Assigning models by drag and drop in the Unity editor works without any issues.
However, when I use the code below in my C# script, I get an error.

my code : 
byte[] modelValues = File.ReadAllBytes(_modelPath);
                        Unity.Barracuda.NNModel nnmodel = ScriptableObject.CreateInstance<Unity.Barracuda.NNModel>();
                        nnmodel.modelData = ScriptableObject.CreateInstance<Unity.Barracuda.NNModelData>();
                        nnmodel.modelData.Value = modelValues;
                        nnmodel.name = "sa_agent";

                        rl_env.GetComponent<shooting_env>().AgentsList[0].Agent.GetComponent<BehaviorParameters>().Model = nnmodel;



Error Msg : 
NotSupportedException: Format version not supported: 244
Unity.Barracuda.ModelLoader+<LoadAsync>d__11.MoveNext () (at Library/PackageCache/com.unity.barracuda@2.4.0-preview/Barracuda/Runtime/Core/ModelLoader.cs:223)
Unity.Barracuda.ModelLoader.Load (System.IO.BinaryReader fileReader, System.Boolean verbose, System.Boolean applyPatching, System.Boolean skipWeights) (at Library/PackageCache/com.unity.barracuda@2.4.0-preview/Barracuda/Runtime/Core/ModelLoader.cs:200)
Unity.Barracuda.ModelLoader.Load (System.Byte[] stream, System.Boolean verbose, System.Boolean skipWeights) (at Library/PackageCache/com.unity.barracuda@2.4.0-preview/Barracuda/Runtime/Core/ModelLoader.cs:140)
Unity.Barracuda.ModelLoader.Load (Unity.Barracuda.NNModel model, System.Boolean verbose, System.Boolean skipWeights) (at Library/PackageCache/com.unity.barracuda@2.4.0-preview/Barracuda/Runtime/Core/ModelLoader.cs:31)
Unity.MLAgents.Editor.BehaviorParametersEditor.DisplayFailedModelChecks () (at Library/PackageCache/com.unity.ml-agents@2.1.0-exp.1/Editor/BehaviorParametersEditor.cs:153)
Unity.MLAgents.Editor.BehaviorParametersEditor.OnInspectorGUI () (at Library/PackageCache/com.unity.ml-agents@2.1.0-exp.1/Editor/BehaviorParametersEditor.cs:91)
UnityEditor.UIElements.InspectorElement+<>c__DisplayClass59_0.<CreateIMGUIInspectorFromEditor>b__0 () (at <31768fe99cfe4466aa4a401169fb2ce5>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)

**Comment by FlorentGuinier** [comment] 2022-02-21 07:58
Seems the same looking at the callstack/code indeed. So probably same solution as above? Alternatively just use the simple way to load model: https://docs.unity3d.com/Packages/com.unity.barracuda@2.4/manual/Loading.html

**Comment by jhlee0918** [comment] 2022-02-21 08:23
@FlorentGuinier  
Thanks for posting a reply.
Your link is what I tried before.

In the last line of my code, the agent's BehaviorParameters.Model is Barracuda.NNModel.

Do you know how to convert Brracuda.model to Barracuda.NNModel?


                        var modelBin = Resources.Load<Unity.Barracuda.NNModel>(_modelPath);
                        var model = Unity.Barracuda.ModelLoader.Load(modelBin);
                        
                        rl_env.GetComponent<shooting_env>().AgentsList[0].Agent.SetModel("basic_agent", model); // Error miss matching param type 


>>> Agent.SetModel( string behaviorName, Barracuda.NNModel model) // model is not nnmodel

**Comment by FlorentGuinier** [comment] 2022-02-21 10:27
> Do you know how to convert Brracuda.model to Barracuda.NNModel?

A **NNModel** is the byte stream representation of the model as serializable data.
To be exact this byte[] can be accessed by` NNModel.modelData.Value`

A Model is the object oriented model as usable by Barracuda. 

You can take an NNModel and "Load" it to get a Model using
`ModelLoader.Load(myNNModel);`

I'm not sure converting back from the object oriented model to the serializable version is what you want, but if so you could use: ModelWriter.cs::Save() method. As we do when we import an ONNX file to serialize the NNModel asset see https://github.com/Unity-Technologies/barracuda-release/blob/b1eac6c34b12b1ef5506fb7121a29eda2997efd1/Barracuda/Editor/ONNXModelImporter.cs#L72.

**Comment by jhlee0918** [comment] 2022-02-21 10:44
@FlorentGuinier  Thanks for replying again.
The reason for insisting on NNModel is because it rejects the Model in the agent's behaviorParameters.(Image) 

![image](https://user-images.githubusercontent.com/15049967/154938934-64cf2793-9bf9-4454-8152-43595a12046a.png)

If this isn't work, I have to manually insert dozens or hundreds sessions. lol


                        byte[] model = File.ReadAllBytes(_modelPath);
                        var asset = ScriptableObject.CreateInstance<Unity.Barracuda.NNModel>();
                        asset.modelData = ScriptableObject.CreateInstance<Unity.Barracuda.NNModelData>();
                        asset.modelData.Value = model;

                        rl_env.GetComponent<shooting_env>().AgentsList[0].Agent.SetModel("basic_agent", asset);

**Comment by FlorentGuinier** [comment] 2022-02-21 10:53
I think the best would be to ask ML-Agent what is the right approach there then. Maybe using there [forum](https://forum.unity.com/forums/ml-agents.453/) ?

**Comment by jhlee0918** [comment] 2022-02-21 11:05
@FlorentGuinier No, I don't use it.
However, when I checked the call stack of the part where the error occurred, I confirmed that the error occurred in the question because the version of the model was low, and I am training the model again as a last resort.

I thought 244 was the error code number, but it wasn't, it was just the name of the Barracuda version.... I'm cursing myself for not being good at English.

To be honest, it's not a job I really like, and I think my boss might kill me.

**Comment by FlorentGuinier** [comment] 2022-02-21 12:35
`Unity.MLAgents.Editor.BehaviorParametersEditor.DisplayFailedModelChecks () (at Library/PackageCache/com.unity.ml-agents@2.1.0-exp.1/Editor/BehaviorParametersEditor.cs:153)`
The callstack above shows the ML-Agent package?

> I confirmed that the error occurred in the question because the version of the model was low, and I am training the model again as a last resort.

I would advice to export an untrained (or very quickly trained) model while iterating on importing problems or on model architecture. Also without having the full context i feel the problem here is around the code here rather than the model. You could probably try any model actually to confirm maybe?

**Comment by jhlee0918** [comment] 2022-02-22 02:49
![image](https://user-images.githubusercontent.com/15049967/155053931-5194dd35-208d-4c96-8f34-779f86f234e4.png)

Thank you for your interest.
Even after re-training, the same exception handling continues because the version of the model does not match here.

(The required version is 244, but the model I trained on is 20.)

**Comment by jhlee0918** [comment] 2022-02-22 08:01
@FlorentGuinier 
[basic_agent.zip](https://github.com/Unity-Technologies/barracuda-release/files/8114730/basic_agent.zip)
 
This is the model onnx file where the problem occurred.
(Not only this file, but all the files I just created without anything are not horde in my way. )

**Comment by FlorentGuinier** [comment] 2022-02-22 09:06
@jhlee0918 As talked/discussed above i don't think the problem come from the model but from the code itself, so i don't think iterating on the model architecture is the right approach here.

**Comment by jhlee0918** [comment] 2022-02-22 11:06
@FlorentGuinier  Thank you for answer. I'm try to find the problem in the code.

**Comment by jhlee0918** [comment] 2022-02-22 11:25
@FlorentGuinier  I solved it! 
Thank you!! 

uisng AssetDatabase 
model path : 
![image](https://user-images.githubusercontent.com/15049967/155122718-b71c695e-fdab-4bd2-96bb-86c9585ed88e.png)

model load from assets path 
![image](https://user-images.githubusercontent.com/15049967/155122576-8ee43721-6498-4242-bd15-f363ce69c4c7.png)

As you might expect, the code problem is correct. Thank you so much for your help.
