### ISSUE TITLE
I Find ComputeRef is more faster then other 'workers'(Compute and ComputePrecompiled)

### ISSUE THREAD

**Issue by likemango** [Unity-Technologies/barracuda-release#230] opened 2021-10-09 10:28 UTC
My model is FSCRNN[https://arxiv.org/abs/1608.00367](url),it is a sample network for Image Super Resolution . I use barracuda like this:
1. Load the onnx file(trained and export by pytorch) and create a 'worker'
2. Give a low resolution Image to create inputTensor as Input
3. Do 'worker.Excute' function and convert Output tensor to RenderTexture
Code:
`
   model = ModelLoader.Load(onnxModel);
   worker = WorkerFactory.CreateWorker(**WorkerFactory.Type.ComputeRef**,model);
   curTensor = new Tensor(lowImageInput,4);
   var output = worker.Execute(curTensor).PeekOutput();
   output.ToRenderTexture(outputRenderTex);
   Debug.Log("Process Once");
   curTensor.Dispose();
`
I do it in the Start Function,and the result(RenderTexure) is right(same as pytorch).Then I do it in Update Function, to get a fastest process,I have tried different barracuda GPU settings(ComputeRef, Compute and ComputePrecompiled),the problem is when I as **WorkerFactory.Type.ComputeRef** the FPS is more then 150,but other two settings(Compute and ComputePrecompiled) is only 10 or less. This is contrary to what the document describes(ComputeRef is  less efficient).I don't know how it works,Very much hope to get a reply！

**Comment by Aurimasp** [comment] 2021-10-11 12:52
Hi likemango, could you share your onnx model with us?

**Comment by AlexRibard** [comment] 2021-10-11 20:22
Also on which hardware are you testing on?

**Comment by likemango** [comment] 2021-10-12 02:22
> Hi likemango, could you share your onnx model with us?
model(.onnx) and datas(input and output) : [https://drive.google.com/drive/folders/1kQDKclF0GnJhHtqnf76CYE9HfQg5NCAD?usp=sharing](url)

**Comment by likemango** [comment] 2021-10-12 02:24
> Also on which hardware are you testing on?

unity2020.3.17 and barracuda2.2.1-preview
CPU : Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz   3.60 GHz
GPU : NVIDIA GeForce GTX 1660

**Comment by likemango** [comment] 2021-10-12 02:24
> Hi likemango, could you share your onnx model with us?

model(.onnx) and datas(input and output) : https://drive.google.com/drive/folders/1kQDKclF0GnJhHtqnf76CYE9HfQg5NCAD?usp=sharing

**Comment by Aurimasp** [comment] 2021-10-12 09:01
I was able to reproduce this issue locally. **Compute** and **ComputePrecompiled** is around 40 times slower than **ComputeRef** on this model. **Semaphore.WaitForSignal** process is taking a lot of time.

Thanks for reporting the issue. We will take a look into this. 

<img width="839" alt="image" src="https://user-images.githubusercontent.com/26163719/136925921-cd8caf7f-e941-4dad-8ed5-b9ae8e96b114.png">

**Comment by AlexRibard** [comment] 2021-10-12 14:55
Ok I found what the issue is:
Our ConvTranspose implementation in Compute worker is unfortunately sub-optimal for large strides/kernelsize.
Thanks for raising the issue up, as we missed this case.
I'll do a fallback to another implementation for large strides. Things should get faster.

@likemango are you ok with using ComputeRef implementation for now?

**Comment by AlexRibard** [comment] 2021-10-13 00:28
One last thing, there is actually a bug in our ConvTranspose implementation.
So expect the model to output wrong results in latest build (even on computeref).
Both fixes to inference and performance have been pushed and will land in an upcoming version

**Comment by AlexRibard** [comment] 2021-10-13 00:28
(closing thread for now, but feel free to comment more if you need help)

**Closed as completed by AlexRibard** 2021-10-13 00:28 UTC
Labels: performance

**Comment by likemango** [comment] 2021-10-13 05:35
> One last thing, there is actually a bug in our ConvTranspose implementation. So expect the model to output wrong results in latest build (even on computeref). Both fixes to inference and performance have been pushed and will land in an upcoming version

 Thanks a lot , Looking forward to the new version of barracuda !  There is another problem (I don't know if it is caused by the bug of  ConvTranspose implementation) : The output RenderTexture of  'computeRef' and 'compute/computePrecompiled' are quite different, the 'ComputeRef' have many 'Pixel Cube' or 'Pixel Grid' on the Texture,  but 'compute/computePrecompiled' looks right (same as pytorch output). 

By the way, I do the model implementation myself by ComputeShader, and the result is almost correct. What troubles me is the efficient of my implementation. It wroks like this :
1. Read model parameters by json and save in script as 'float[]'.
2. Create ComputeBuffer and use 'Setdata' to set model parameters in it.
3. Do dispatch ComputeShader kernel for each layer of model's network(extract/shrink/map1/map2/map3/map4/expand/ConvTranspose) to get final output. I create ComputeBuffer to store the output of each layer and set all those computeBuffer as  'Shader.SetGlobalBuffer'. So there can access by different ComputeShader's kernel. 

So,the process of implementation just like this: do 'first kernel' ,store the output in 'first buffer', then use' first buffer' to do 'second kernel' caculation ,and store the output in ' second buffer' for third kernel caculation.. and so on,main code is under blow:
![MyImplementation](https://user-images.githubusercontent.com/40531806/137071782-680b7343-5cc5-48a2-85d1-4df7679d28e4.png)
It works,but less than 10FPS in Update Function. Is there have any suggests to improve the effecient ? or where and how I can find the process pipeline of the 'Worker's Excute' function in barracuda, I gona learn from it. 
Very much looking forward to your help!

**Comment by AlexRibard** [comment] 2021-10-13 17:48
With current fixes, we get the same output for your model as onnxruntime/pytroch at 10e-4 absolute/relative error.
So things will be correct once we ship the latest version.
We are about to release it, so I expect that you shouldn't need to wait long.

Internally, we do the inference the same way as your custom code.
But we spend a lot of time optimizing the kernels, so I would hope that performance is better.
I'd say, keep relying on our worker.
A few things you could try:
* You can try changing `ComputeInfo.channelsOrder` to `ChannelsOrder.NCHW` that shaves off a few ms.
* Also reducing input image size might be worth while.
* Most of the cost of the model is in the last `ConvTranspose`, if you can reduce the krenel size a bit that would save some ms too
* You can also split execution in two frames, so run the first `Conv` layers one frame and the last `ConvTranspose` in the last frame.
Like so https://github.com/Unity-Technologies/barracuda-release/blob/release/1.0.0/Documentation~/ModelExecution.md

**Comment by likemango** [comment] 2021-10-14 08:49
> With current fixes, we get the same output for your model as onnxruntime/pytroch at 10e-4 absolute/relative error. So things will be correct once we ship the latest version. We are about to release it, so I expect that you shouldn't need to wait long.
> 
> Internally, we do the inference the same way as your custom code. But we spend a lot of time optimizing the kernels, so I would hope that performance is better. I'd say, keep relying on our worker. A few things you could try:
> 
> * You can try changing `ComputeInfo.channelsOrder` to `ChannelsOrder.NCHW` that shaves off a few ms.
> * Also reducing input image size might be worth while.
> * Most of the cost of the model is in the last `ConvTranspose`, if you can reduce the krenel size a bit that would save some ms too
> * You can also split execution in two frames, so run the first `Conv` layers one frame and the last `ConvTranspose` in the last frame.
>   Like so https://github.com/Unity-Technologies/barracuda-release/blob/release/1.0.0/Documentation~/ModelExecution.md

Thank you very much for your reply ! I will dive in it.
