### ISSUE TITLE
NonMaxSuppression operation returns invalid/arbritray result when no boxes are detected

### ISSUE THREAD

**Issue by fmannhardt** [Unity-Technologies/barracuda-release#173] opened 2021-05-06 09:16 UTC
We have an issue when using the NMS operator in ONNX in the most recent Barracuda version (1.4.0). When the model does not detect any boxes, there are anyway some results returned from the NMS operator. All with confidence score close to 0. 

I debugged the error until the code here:
https://github.com/Unity-Technologies/barracuda-release/blob/76077c0b2de7254b4f559a398a622cda072e7bf5/Barracuda/Runtime/Core/Backends/BarracudaReferenceCPU.cs#L3119

A new Tensor is allocated, which will always be of at least size 3 (shape 0,1,1,3) when there are no boxes selected at all. This Tensor seems to be filled with random values, which are then interpreted by the following layers/operators of the neural network. This may actually lead to reading beyond the Tensor boundaries and cause errors since the result of the NMS operator are used as indices.

**Comment by FlorentGuinier** [comment] 2021-05-06 09:29
@fmannhardt Thanks for feedback and debugging! We will look into it.

**Comment by amirebrahimi** [comment] 2021-05-07 00:28
Thanks, @fmannhardt - confirmed on our end. Will report back when this is fixed.

**Comment by FlorentGuinier** [comment] 2021-05-07 12:54
Issue has been converted to Unity bug: https://issuetracker.unity3d.com/product/unity/issues/guid/BAR-93 closing.

**Closed as completed by FlorentGuinier** 2021-05-07 12:54 UTC

**Comment by amirebrahimi** [comment] 2021-05-08 01:53
@fmannhardt - after looking into this it would be a more significant change to our runtime because currently we don't support empty tensors. If there was a single entry with all 0s instead of random data would that work for you still? Perhaps you could validate with a WHERE or IF layer?

**Comment by fmannhardt** [comment] 2021-05-10 21:14
This is, of course, not optimal since it breaks the specification or at least the common sense implementation of the ONNX NMS layer. I assume that the indicies are 0 indexed, so returning all 0s would be unlikely but a valid actual result, wouldn't it? 

Then, I guess a negative value would be better. I have not looked at the `If` and `Where` operators defined in ONNX, but it seems that would be an option. I am using a `Gather` layer to get the results of the NMS layer.

**Comment by amirebrahimi** [comment] 2021-05-17 19:53
Yes, you're right, -1s would be much better. I can make this change in the meantime to help unblock you. You'd see this change in the next preview release.
