### ISSUE TITLE
Keras LSTM Model converted to .onnx results in error in Unity

### ISSUE THREAD

**Issue by yfedberts** [Unity-Technologies/barracuda-release#98] opened 2020-10-24 12:24 UTC
I have a keras model converted to .onnx however when I attempt to insert it into Unity, it does not work. Any advice? I've tried keras2onnx and onnxmltools but alas same results. Can't find any information regarding this online.

The following error was produced.

```
Asset import failed, "Assets/Models/LSTM-Model.onnx" > KeyNotFoundException: The given key was not present in the dictionary.
System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) (at <fb001e01371b4adca20013e0ac763896>:0)
Unity.Barracuda.ONNX.ONNXModelConverter.BuildNodeSkipList (Onnx.GraphProto graph) (at Library/PackageCache/com.unity.barracuda@071ded3dad/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:1383)
Unity.Barracuda.ONNX.ONNXModelConverter.ConvertOnnxModel (Onnx.ModelProto onnxModel) (at Library/PackageCache/com.unity.barracuda@071ded3dad/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:1153)
Unity.Barracuda.ONNX.ONNXModelConverter.Convert (Google.Protobuf.CodedInputStream inputStream) (at Library/PackageCache/com.unity.barracuda@071ded3dad/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:82)
Unity.Barracuda.ONNX.ONNXModelConverter.Convert (System.String filePath) (at Library/PackageCache/com.unity.barracuda@071ded3dad/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:60)
Unity.Barracuda.ONNXModelImporter.OnImportAsset (UnityEditor.Experimental.AssetImporters.AssetImportContext ctx) (at Library/PackageCache/com.unity.barracuda@071ded3dad/Barracuda/Editor/ONNXModelImporter.cs:44)
UnityEditor.Experimental.AssetImporters.ScriptedImporter.GenerateAssetData (UnityEditor.Experimental.AssetImporters.AssetImportContext ctx) (at <9ddd600ae5964fe0b21a870e08c53748>:0)
```

Thanks in advance!

**Comment by AlexRibard** [comment] 2020-10-26 16:04
Hello @Mystickal LSTM requires some surgery to get working properly in Barracuda atm.
Could you provide your onnx model so we can look into it in more details?

Thanks!

**Comment by yfedberts** [comment] 2020-10-26 16:27
> 
> 
> Hello @Mystickal LSTM requires some surgery to get working properly in Barracuda atm.
> Could you provide your onnx model so we can look into it in more details?
> 
> Thanks!

Hello, @AlexRibard thanks for the reply! Yes definitely, the file attached here is the onnx along with the .h5 file, and the snippet below is the codes behind the LSTM model:

```
n_timesteps, n_features, n_outputs = trainX.shape[1], trainX.shape[2], trainy.shape[1]
model = Sequential()
model.add(LSTM(100, input_shape=(n_timesteps,n_features)))
model.add(Dropout(0.5))
model.add(Dense(100, activation='relu'))
model.add(Dense(n_outputs, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
# fit network
history = model.fit(trainX, trainy, epochs=15, batch_size=64, verbose=1,
validation_data=(testX,testy), validation_batch_size=64)
```
[LSTM-Model_10-27-2020_00-26-40.zip](https://github.com/Unity-Technologies/barracuda-release/files/5440048/LSTM-Model_10-27-2020_00-26-40.zip)

Thanks for your time!

**Comment by yfedberts** [comment] 2020-10-30 12:31
Hi, @AlexRibard ! Sorry, just checking in did you have any insight or luck finding the issues with the model?

**Comment by AlexRibard** [comment] 2020-10-30 17:58
Sorry, I have been busy. @mantasp you want to look into this one?

**Comment by yfedberts** [comment] 2020-11-02 05:47
@AlexRibard @mantasp It's fine I appreciate the help, apologies for barging in but would it be possible to provide a working LSTM Model or some insight as to where the problem usually lies for debugging purposes?

**Comment by AlexRibard** [comment] 2020-11-02 15:13
@Mystickal shoot us an email at barracuda-support@unity3d.com
We are working on a tutorial on the topic, as running LSTM is slightly tricky in barracuda.
I'll send you the details.

**Comment by yfedberts** [comment] 2020-11-02 15:29
@AlexRibard 
Okay, sent thanks!

**Comment by FD-MINGJIE** [comment] 2021-01-21 06:38
@Mystickal @AlexRibard:
   Could you please send me some details about LSTM via email?
   Thanks!

**Comment by akaimody123** [comment] 2021-02-01 16:16
@Mystickal @AlexRibard @FD-MINGJIE 
Hi, I'm having the same issue, could you please send me some details about it? My email is ucabbz2@ucl.ac.uk
Many thanks!

**Comment by AlexRibard** [comment] 2021-02-01 16:53
Hi guys! We are working on making LSTM work without any special setup!
If you could link us your models we'd be happy to validate that it works on latest.
Let me know

**Comment by akaimody123** [comment] 2021-02-01 18:05
@AlexRibard Thank you for the reply! I have sent you my model by email.

**Comment by FD-MINGJIE** [comment] 2021-02-02 07:32
@AlexRibard 
[two_layers_LSTM.zip](https://github.com/Unity-Technologies/barracuda-release/files/5909333/two_layers_LSTM.zip)

**Comment by buzziolg** [comment] 2021-02-08 07:04
@AlexRibard Hi, having the same issue as well. Here's my model if you could/want to validate it as well.
[LSTM_CNN.zip](https://github.com/Unity-Technologies/barracuda-release/files/5941796/LSTM_CNN.zip)

**Comment by AlexRibard** [comment] 2021-02-08 19:49
Thank you for your models, we are working actively to make them all work

**Comment by amirebrahimi** [comment] 2021-03-22 17:53
This work is now complete and will be included in v1.3.3.

**Closed as completed by amirebrahimi** 2021-03-22 17:53 UTC

**Comment by smasish** [comment] 2021-03-23 20:38
[model.zip](https://github.com/Unity-Technologies/barracuda-release/files/6192583/model.zip)
@AlexRibard  I got the same issue. Here is my cnn-lstm model.

**Comment by amirebrahimi** [comment] 2021-03-23 22:48
@smasish can you send me an onnx exported version?

**Comment by smasish** [comment] 2021-03-24 00:32
@amirebrahimi I can't convert h5 to onnx format. That's why I posted if someone can help me to convert cnn-lstm model h5 fromat to onnx .

**Comment by amirebrahimi** [comment] 2021-03-24 00:48
@smasish - try using https://github.com/onnx/keras-onnx

**Comment by AlexRibard** [comment] 2021-03-24 01:07
Code should be pretty straightforward:
```
import argparse
import onnxmltools
from keras.models import load_model

...

keras_model = load_model(input_keras_model)
onnx_model = onnxmltools.convert_keras(keras_model)
onnxmltools.utils.save_model(onnx_model, output_onnx_model)
```

**Comment by smasish** [comment] 2021-03-24 01:39
@AlexRibard  I run the same code to convert my cnn-lstm model but it throws the following error. 

TypeError: must be str, not NoneType

**Comment by amirebrahimi** [comment] 2021-03-24 02:17
Are you passing the path to your .h5 file to `load_model()`?

**Comment by smasish** [comment] 2021-03-24 15:55
@amirebrahimi  Yes, here is the code
keras_model = load_model('C:/Users/admin/Desktop/All ML result4/cnnlstm/model_CNNLSTM_norm.h5')
onnx_model = onnxmltools.convert_keras(keras_model)
onnxmltools.utils.save_model(onnx_model, output_onnx_model)

Error is showing for 2nd line -  onnxmltools.convert_keras.
TypeError: must be str, not NoneType

**Comment by AlexRibard** [comment] 2021-03-24 15:57
Yeah I tried also with 
```
import tensorflow as tf
import onnx
import keras2onnx

input_keras_model = "model_CNNLSTM.h5"
output_onnx_model = "model_CNNLSTM.onnx"

model = tf.keras.models.load_model(input_keras_model)
onnx_model = keras2onnx.convert_keras(model)

onnx.save(onnx_model, output_onnx_model)
```

From what I got from searching the issue is that keras2onnx doesn't work well with tf2.
I would open a ticket on their github

**Comment by smasish** [comment] 2021-03-30 20:56
@AlexRibard  Have you fixed this converting issue?

**Comment by amirebrahimi** [comment] 2021-03-30 22:04
@smasish - this seems to be a bug with their exporter. As @AlexRibard suggested it would be best to add a comment to this [pre-existing issue](https://github.com/onnx/keras-onnx/issues/665) and see if you can work around the export issue. I'd suggest bisecting your model until you can pinpoint what may be causing the issue. Unfortunately, there's not much more we can do here.

**Comment by AlexRibard** [comment] 2021-04-01 16:47
@smasish yeah the problem is really on `keras2onnx` side.
Are you able to re-create your model in pytroch? Should be ok no?
