### ISSUE TITLE
Difference in behaviour between ONNX runtime and Barracuda

### ISSUE THREAD

**Issue by martoko** [Unity-Technologies/barracuda-release#218] opened 2021-08-18 15:51 UTC
Output using ONNX Runtime through Python
![image](https://user-images.githubusercontent.com/18300234/129927538-6c52e5f3-5d79-4cbb-8ea7-b1814f9ecb60.png)

Output using Barracuda through Unity
![image](https://user-images.githubusercontent.com/18300234/129927595-8553dfdc-3632-4432-924d-b473966fa1ec.png)

The model used:
[simp_repl.zip](https://github.com/Unity-Technologies/barracuda-release/files/7008408/simp_repl.zip)

The input for both invocations are just a long string of "0101010101..." for testing purposes. Here is the code generating the input:
```c#
        var model = ModelLoader.Load(_resources);
        _size = model.inputs[0].shape[6]; // Input tensor width
        _worker = model.CreateWorker(device:WorkerFactory.Device.GPU, true);
        var data = new float[_size * _size * 3];
        for (int i = 0; i < _size * _size * 3; i++)
        {
            data[i] = i % 2;
        }

        using (var tensor = new Tensor(1, _size, _size, 3, data))
            _worker.Execute(tensor);
        var t = _worker.PeekOutput();
        Debug.Log(t);
        var builder = new StringBuilder();
        for (int i = 0; i < 17; i++)
        {
            var x = t[0, 0, i, 0];
            var y = t[0, 0, i, 1];
            var c = t[0, 0, i, 2];
            builder.Append($"{x}, {y}, {c}\n");
        }
        Debug.Log(builder);
```

Running it on the CPU gives an error related to multiplication:
```
Layer: Mul StatefulPartitionedCall/mul_2

AssertionException: Assertion failure. Value was False
Expected: True
UnityEngine.Assertions.Assert.Fail (System.String message, System.String userMessage) (at <a0ef933b1aa54b668801ea864e4204fe>:0)
UnityEngine.Assertions.Assert.IsTrue (System.Boolean condition, System.String message) (at <a0ef933b1aa54b668801ea864e4204fe>:0)
UnityEngine.Assertions.Assert.IsTrue (System.Boolean condition) (at <a0ef933b1aa54b668801ea864e4204fe>:0)
Unity.Barracuda.ReferenceCPUOps.NewTensorLike (Unity.Barracuda.Tensor[] tensors) (at Library/PackageCache/com.unity.barracuda@2.1.0-preview/Barracuda/Runtime/Core/Backends/BarracudaReferenceCPU.cs:353)
Unity.Barracuda.BurstCPUOps.Mul (Unity.Barracuda.Tensor[] tensors) (at Library/PackageCache/com.unity.barracuda@2.1.0-preview/Barracuda/Runtime/Core/Backends/BarracudaBurstCPU.Ops.cs:1366)
Unity.Barracuda.VerboseOps.Unity.Barracuda.IOps.Mul (Unity.Barracuda.Tensor[] tensors) (at Library/PackageCache/com.unity.barracuda@2.1.0-preview/Barracuda/Runtime/Core/Backends/VerboseOps.cs:676)
Unity.Barracuda.StatsOps.Unity.Barracuda.IOps.Mul (Unity.Barracuda.Tensor[] tensors) (at Library/PackageCache/com.unity.barracuda@2.1.0-preview/Barracuda/Runtime/Core/Backends/StatsOps.cs:720)
Unity.Barracuda.GenericWorker+<StartManualSchedule>d__33.MoveNext () (at Library/PackageCache/com.unity.barracuda@2.1.0-preview/Barracuda/Runtime/Core/Backends/GenericWorker.cs:573)
Unity.Barracuda.GenericWorker.Execute () (at Library/PackageCache/com.unity.barracuda@2.1.0-preview/Barracuda/Runtime/Core/Backends/GenericWorker.cs:160)
Unity.Barracuda.GenericWorker.Execute (Unity.Barracuda.Tensor input) (at Library/PackageCache/com.unity.barracuda@2.1.0-preview/Barracuda/Runtime/Core/Backends/GenericWorker.cs:152)
BodyDetector.Start () (at Assets/Test/Script/BodyDetector.cs:33)
```

**Comment by AlexRibard** [comment] 2021-08-18 20:17
Thanks for providing the model as well as the reprocase.
On what Barracuda version are you?
I've tried to run your model. I'm still getting some discrepancies but the output tensor is not totally empty like yours.
CPU runs without errors (same differences compared to onnx though)

**Comment by AlexRibard** [comment] 2021-08-18 21:07
Thanks for providing the model as well as the reprocase.
I've investigated the model and the issue comes from this part:
![image](https://user-images.githubusercontent.com/12990800/129972160-75a9e696-8c84-4d16-b4c5-7fc927eba685.png)
We do not distinguish from `float` and `int` operations. So dividing the ArgMax by 48 and then * by 48 will result in the same value as ArgMax. Leaving the Sub output to be 0.
I'd suggest to add a `Floor` after the Div op to make sure things are rounded down:
https://github.com/onnx/onnx/blob/master/docs/Operators.md#Floor

**Comment by martoko** [comment] 2021-08-19 08:50
Ahh, I see. The fact that barracuda casts are no-ops is a pretty significant detail, I seem to have missed.

Thank you for informing me and for your suggestion, adding the floor does seem like it would fix the modulus operation.

**Comment by AlexRibard** [comment] 2021-08-19 19:50
Yeah, we should make that clearer in the documentation, you are right.
I'll close this thread for now. Feel free to share the modified model / re-open this thread if you still have trouble after!

**Comment by martoko** [comment] 2021-08-20 15:34
It would seem that I am still having trouble. 😅 

The original model, provided for reference:
[simp.zip](https://github.com/Unity-Technologies/barracuda-release/files/7022505/simp.zip)

The model with my changes to workaround barracuda limitations/differences (This is the model that behaves weirdly):
[simp_repl.zip](https://github.com/Unity-Technologies/barracuda-release/files/7022507/simp_repl.zip)

So I have updated it using a floor like you suggested and also a floor after casting to int, but something is still going wrong and I can't quite figure out what. The output is now:
![image](https://user-images.githubusercontent.com/18300234/130255317-c2a3819e-48e8-410a-8f5b-ae01328cf1d1.png)

As a side note: I have tested it without the "post-processing" part, by cutting off the last part of the model, and that gives the same results for both barracuda and the ONNX runtime. It is what happens after the 4 "bias1" nodes shown below, that causes barracuda to behave differently compared to the ONNX runtime. The cut off model:
[model_cut_off_before_gathernds.zip](https://github.com/Unity-Technologies/barracuda-release/files/7022520/model_cut_off_before_gathernds.zip)
![image](https://user-images.githubusercontent.com/18300234/130255643-fc730765-dc04-4f52-b95f-942fde881a2c.png)

The python code used for testing the ONNX runtime:
```python
import numpy as np
import onnx
import onnxruntime

# img = np.random.rand(1, 192, 192, 3).astype(np.uint8)
img = np.zeros(192 * 192 * 3)
for i in range(192 * 192 * 3):
    img[i] = i % 2
img = img.reshape((1, 192, 192, 3)).astype(np.uint8)

sess = onnxruntime.InferenceSession("model_cut_off_before_gathernds.onnx")

print("The model expects input shape: ", sess.get_inputs()[0].shape)
print("The shape of the Image is: ", img.shape)

input_name = sess.get_inputs()[0].name
label_name = sess.get_outputs()[0].name
result = sess.run(None, {input_name: img})
for t in result:
    print(t.shape)
    print(t)
print()
```

**Comment by FlorentGuinier** [comment] 2021-08-23 09:57
Hi Martoko, 

Could you say the version of Barracuda you are using please? I just tested the above simp_repl.onnx locally (bleeding edge Barracuda, soon to be released as 2.2.0) and got sensible result:

0.3868844 0.4556777 0.03352159 
0.3605231 0.4963068 0.04544374 
0.3911542 0.4505024 0.0330055 
0.3762081 0.5017632 0.02208734 
0.4526926 0.5439589 0.02172523 
0.4009603 0.6869432 0.00625425 
0.4258535 0.4608708 0.01527943 
0.4486957 0.7001659 0.007894098 
0.3624319 0.02413511 0.10355 
0.5090598 0.6053963 0.009371907 
0.5517415 0.4452464 ...

So this might be a bug present in a previous version?

**Comment by martoko** [comment] 2021-08-23 11:33
I am not at the computer right now, but I think it was 2.1.0 I can get back
with exact details in a few days. But if works in the "dev" version, you
can feel free to close the issue, as all I would need to do is update
(possibly wait for the release first)

2021年8月23日(月) 11:57 Florent Guinier ***@***.***>:

**Comment by AlexRibard** [comment] 2021-08-23 13:51
@martoko yeah the issue is probably `Gather`, we recently had some fixes for it.
If our release is taking too long, I'll send you a patch.

**Closed as completed by AlexRibard** 2021-08-23 13:51 UTC
