### ISSUE TITLE
Error when moving between preview package versions

### ISSUE THREAD

**Issue by ROBYER1** [Unity-Technologies/barracuda-release#120] opened 2020-12-18 11:20 UTC
When upgrading/downgrading between 1.2.0 and 1.2.1 I consistently get this error in Unity 2020.2.0f1 in an Android project:

`Microsoft (R) Visual C# Compiler version 3.5.0-dev-20359-01 (8da8ba0c)
Copyright (C) Microsoft Corporation. All rights reserved.

error CS0006: Metadata file 'D:/Unity Projects/Unity_Detection2AR/Library/PackageCache/com.unity.barracuda@1.2.0-preview/Barracuda/Runtime/Plugins/ProtoBuffer/Google.Protobuf.dll' could not be found
`

This error doesn't clear until you close/reopen the project

**Comment by Aurimasp** [comment] 2021-01-06 09:50
Hey, thanks for sharing this issue. Could you please share an example project with us? I can't reproduce it locally.

**Comment by ROBYER1** [comment] 2021-01-06 14:22
> Hey, thanks for sharing this issue. Could you please share an example project with us? I can't reproduce it locally.

This only happens with Visual Studio Community 2019 not VS Code I noticed, what IDE are you using? I don't mind if this issue is closed as it's not a major issue.

**Comment by Aurimasp** [comment] 2021-01-07 06:15
I'm usually using Rider. I've just tried to test it with Visual Studio Community, but the issue doesn't reproduce on my machine with it. Does it reproduce on other machines? I believe there may be a lot of environmental variables responsible for it.

Sure, I'll close the issue. If you'll discover some more clues about it or this issue gets bothersome, feel free to reach us again.

**Closed as completed** 2021-01-07 06:19 UTC
