### ISSUE TITLE
Thread group count is above the maximum allowed limit

### ISSUE THREAD

**Issue by abigos** [Unity-Technologies/barracuda-release#220] opened 2021-08-25 21:10 UTC
Hi,

This is related to a previous issues the that isn't reported as fixed : https://github.com/Unity-Technologies/barracuda-release/issues/67 but it's slightly different.

Log is below with version details etc..  The use case it a network which can take an arbitrary input and produce an arbitrary size input,  for example 512x512 (x,y) in and 512x512 (rgb) out.  512 actually works fine - but if I move to a larger size (1024) I get the failure.  

This works fine - if, very very slowly on the C# version, so I'm assuming for GPU you are actually intending to handle this case, e.g.  I wouldn't be expected to split up the input myself and issue multiple executes and then tile the final output texture on GPU .  There seems no mechanism to detect when this would happen at the moment in any case (and it depends on how you allocated threads etc.).

Note that running PrepareForInput with the sizes doesn't through up any error messages or warnings (and has void return).  

In the first instance it would be good to confirm you intend to handle this case or if I should be doing multiple executes.

Thanks,
Andy

`Thread group count is above the maximum allowed limit. Maximum allowed thread group count is 65535.
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Unity.Barracuda.ComputeFunc:Dispatch (int,int,int) (at Library/PackageCache/com.unity.barracuda@2.1.0-preview/Barracuda/Runtime/Core/Backends/BarracudaReferenceCompute.cs:2824)
Unity.Barracuda.ComputeFunc:Dispatch (System.ValueTuple3<int, int, int>) (at Library/PackageCache/com.unity.barracuda@2.1.0-preview/Barracuda/Runtime/Core/Backends/BarracudaReferenceCompute.cs:2801)
Unity.Barracuda.ComputeKernel:Dispatch () (at Library/PackageCache/com.unity.barracuda@2.1.0-preview/Barracuda/Runtime/Core/Backends/BarracudaCompute.cs:926)
Unity.Barracuda.ComputeOps:Dense (Unity.Barracuda.Tensor,Unity.Barracuda.Tensor,Unity.Barracuda.Tensor,Unity.Barracuda.Layer/FusedActivation) (at Library/PackageCache/com.unity.barracuda@2.1.0-preview/Barracuda/Runtime/Core/Backends/BarracudaCompute.cs:1165)
Unity.Barracuda.StatsOps:Unity.Barracuda.IOps.Dense (Unity.Barracuda.Tensor,Unity.Barracuda.Tensor,Unity.Barracuda.Tensor,Unity.Barracuda.Layer/FusedActivation) (at Library/PackageCache/com.unity.barracuda@2.1.0-preview/Barracuda/Runtime/Core/Backends/StatsOps.cs:100)
Unity.Barracuda.GenericWorker/<StartManualSchedule>d__33:MoveNext () (at Library/PackageCache/com.unity.barracuda@2.1.0-preview/Barracuda/Runtime/Core/Backends/GenericWorker.cs:258)
Unity.Barracuda.GenericWorker:Execute () (at Library/PackageCache/com.unity.barracuda@2.1.0-preview/Barracuda/Runtime/Core/Backends/GenericWorker.cs:160)
Unity.Barracuda.GenericWorker:Execute (System.Collections.Generic.IDictionary2<string, Unity.Barracuda.Tensor>) (at Library/PackageCache/com.unity.barracuda@2.1.0-preview/Barracuda/Runtime/Core/Backends/GenericWorker.cs:145)
MLPBarracuda:Update () (at Assets/Runtime/MLPBarracuda.cs:192)
`

**Comment by AlexRibard** [comment] 2021-08-26 15:55
@abigos could you provide the model you are using? That would be useful.
This error comes up when the input size is too big and the dispatch sizes exceed the allowed thread group count.
It doesn't usually happen, but maybe your model has some large dimension which makes us hit this threshold.
We do currently solve this issue for the common cases were it might happen. And we do intend to provide a solution whenever we hit such issues.
But it would require us taking a look at your model.
If you are ok, you can share it via google drive or directly at barracuda-support@unity3d.com 
Let me know

**Comment by abigos** [comment] 2021-08-26 16:33
Hi Alex,

I sent a repro via email.

Thanks,
Andy

**Comment by AlexRibard** [comment] 2021-08-26 16:48
Ok thanks for reaching out.
I'm closing the issue as I know what the issue is.

**Closed as completed by AlexRibard** 2021-08-26 16:48 UTC
