### ISSUE TITLE
yolov4-tiny: barracuda does not support some features for yolov4-tiny?

### ISSUE THREAD

**Issue by AndreySkyFoxSidorov** [Unity-Technologies/barracuda-release#146] opened 2021-02-16 11:55 UTC
Hello. I'm trying to translate the trained neural network into onnx.
For some unknown reason, the neural network does not open in Unity.

Steps:
1. Trained and tested the net in google colab. ( Exemple: https://colab.research.google.com/drive/1PWOwg038EOGNddf6SXDG5AsC8PIcAe-G )
darknet detector train data/obj.data cfg/custom-yolov4-tiny-detector.cfg yolov4-tiny.conv.29 -dont_show -map
and test on 
darknet detector demo data/obj.data cfg/custom-yolov4-tiny-detector.cfg backup/yolov4_tiny_final.weights test.mp4 -i 0

2. translate darknet -> keras-yolo4 -> keras-onnx

3. Load on unity:
![yolo4](https://user-images.githubusercontent.com/10269961/108059030-93ddfb00-705d-11eb-9877-6fc71b3cf828.jpg)

For some unknown reason, the neural network does not open.

Are there any working examples(yolov4-tiny) of how to import correctly into barracuda? 
Is this an import problem or barracuda does not support some features for yolov4-tiny?

**Comment by FlorentGuinier** [comment] 2021-02-16 12:04
Hi AndreySkyFoxSidorov,

We would need a bunch of information to dig into this:
- What barracuda version are you currently using ?
- Could you share the onnx model here (random weight is fine) ?

We have green test for tiny yolov4 (tiny_yolov4_mobilenetv2_lite to be exact), however it would be good to dig into your particular instance of tiny yolov4.

Thanks
Florent

**Comment by AndreySkyFoxSidorov** [comment] 2021-02-17 09:37
Hi Florent,

Thanks for the quick response, 

1. barracuda version 1.3.0
2. I tried 2 ways:
	a) darknet->pytorch->onnx 
	and 
	b) darknet->keras-yolo4->keras-onnx 

to translate, but the result is the same - Do not open in Unity.

[yolov4-tiny_darknet_pytorch_onnx.zip](https://github.com/Unity-Technologies/barracuda-release/files/5994645/yolov4-tiny_darknet_pytorch_onnx.zip)

Thanks
Andrey.

**Comment by FlorentGuinier** [comment] 2021-02-17 10:18
So the problem is 
![image](https://user-images.githubusercontent.com/20201082/108190167-e4169500-7111-11eb-9db9-b72decc6054f.png)

**Comment by FlorentGuinier** [comment] 2021-02-17 10:29
We only support const tensors for `Slice` operator parameters atm:
Input0 can be dynamic but `starts, ends, axes and steps` are only supported from const tensors atm.

A workaround would be to convert to input tensors to const in your model if possible (if input size is known and constant).

**Comment by AndreySkyFoxSidorov** [comment] 2021-02-17 10:44
Thanks for the clarifications. I will sort this out. I think it will be useful to add examples to the Documentation in the future.

**Comment by AlexRibard** [comment] 2021-02-18 16:48
@AndreySkyFoxSidorov I am re-opening your issue as for `Slice` inputs are const at compile time and should be baked down.
I'll let you know when the fixes are in

**Comment by amirebrahimi** [comment] 2021-06-15 20:34
Closing this since it has landed with the release of 2.1.0-preview

**Comment by AlexRibard** [comment] 2021-06-15 20:34
@AndreySkyFoxSidorov it's fixed in 2.1.0-preview

**Closed as completed** 2021-06-15 20:34 UTC

**Comment by Ademord** [comment] 2021-08-16 13:53
@AndreySkyFoxSidorov are there any examples in the docs?
