### ISSUE TITLE
Error with Yolov3-tiny : Unexpected error while parsing layer 58 of type Reshape. Cannot reshape array of size 5 into shape with multiple of 2 elements

### ISSUE THREAD

**Issue by ArnoBen** [Unity-Technologies/barracuda-release#132] opened 2021-01-17 11:17 UTC
Unity 2019.4.18f1
Barracuda 1.2.1

Hello Barracuda team,
I'm trying to use yolov3-tiny exported to onnx from pytorch but I'm getting this error when importing the onnx file in my assets:
```
OnnxImportException: Unexpected error while parsing layer 58 of type Reshape.
Cannot reshape array of size 5 into shape with multiple of 2 elements

Json: { "input": [ "56", "57" ], "output": [ "58" ], "name": "Reshape_20", "opType": "Reshape" }
```

I got the onnx file in a pretty straightforward way using ultralytics repo:

1. Download the yolov3-tiny.pt from here : https://github.com/ultralytics/yolov3/releases
2. Convert it to onnx using this (simply replace their yolov5 weights with the yolov3-tiny ones) : https://github.com/ultralytics/yolov5/issues/251 
3. Import the onnx in Unity

In Netron, the node raising the error is this one :
![image](https://user-images.githubusercontent.com/14088321/104838768-569b1780-58bd-11eb-9bbc-9b0397e2dddf.png)

I tried various things like changing the opversion when converting or using weights trained on custom data, but it still gives me this error. I'm not sure where to look at now, any help would be appreciated.

**Comment by AlexRibard** [comment] 2021-01-17 16:32
@ArnoBen could you provide the full onnx model? (maybe via zip or google drive if it is heavy).
Once you share the model, I'll take a look at it

**Comment by ArnoBen** [comment] 2021-01-17 17:42
@AlexRibard  Sure thing, there you go : https://drive.google.com/file/d/1MkutpVnk8pMp3CGg6cmqjxXuevXZl-BQ/view?usp=sharing
It's 30MB.

**Comment by AlexRibard** [comment] 2021-01-17 18:00
great! thank you

**Comment by ROBYER1** [comment] 2021-01-20 13:39
This repository where we are using Yolov3-tiny may be useful to you also, if I get time I will try your model in our repo
https://github.com/derenlei/Unity_Detection2AR

**Comment by ArnoBen** [comment] 2021-01-21 14:05
Thank you I'll give it a look !

**Comment by fmannhardt** [comment] 2021-03-09 20:03
Any news on this issue? I am getting the same issue on a TinyYOLOv3 trained model based on the PyTorch implementation here:
https://github.com/ultralytics/yolov3/releases
On Barracuda 1.2.0-preview:

```
OnnxImportException: Unexpected error while parsing layer 58 of type Reshape.
Cannot reshape array of size 5 into shape with multiple of 2 elements

Json: { "input": [ "56", "57" ], "output": [ "58" ], "name": "Reshape_20", "opType": "Reshape" }
  at Unity.Barracuda.TensorExtensions.Reshape (Unity.Barracuda.TensorShape shape, System.Int32[] size) [0x0010d] in C:\Users\FelixMannhardt\KIT-AR\code\assist\assist\src-explore\ANNStandalone\Library\PackageCache\com.unity.barracuda@1.2.0-preview\Barracuda\Runtime\Core\TensorExtensions.cs:468 
  at Unity.Barracuda.TensorExtensions.Reshape (Unity.Barracuda.Tensor X, System.Int32[] size) [0x00001] in C:\Users\FelixMannhardt\KIT-AR\code\assist\assist\src-explore\ANNStandalone\Library\PackageCache\com.unity.barracuda@1.2.0-preview\Barracuda\Runtime\Core\TensorExtensions.cs:183 
  at Unity.Barracuda.ONNX.ONNXTensor.Reshape (System.Int32[] onnxShape) [0x0000d] in C:\Users\FelixMannhardt\KIT-AR\code\assist\assist\src-explore\ANNStandalone\Library\PackageCache\com.unity.barracuda@1.2.0-preview\Barracuda\Runtime\ONNX\ONNXTensor.cs:186 
  at Unity.Barracuda.ONNX.ONNXModelConverter+<>c__DisplayClass17_1.<.ctor>b__2 (Unity.Barracuda.ModelBuilder net, Unity.Barracuda.ONNX.ONNXNodeWrapper node) [0x0012b] in C:\Users\FelixMannhardt\KIT-AR\code\assist\assist\src-explore\ANNStandalone\Library\PackageCache\com.unity.barracuda@1.2.0-preview\Barracuda\Runtime\ONNX\ONNXModelConverter.cs:161 
  at Unity.Barracuda.ONNX.ONNXModelConverter.ConvertOnnxModel (Onnx.ModelProto onnxModel) [0x00360] in C:\Users\FelixMannhardt\KIT-AR\code\assist\assist\src-explore\ANNStandalone\Library\PackageCache\com.unity.barracuda@1.2.0-preview\Barracuda\Runtime\ONNX\ONNXModelConverter.cs:1557 

Unity.Barracuda.ONNX.ONNXModelConverter.Err (Unity.Barracuda.Model model, System.String layerName, System.String message, System.String extendedMessage, System.String debugMessage) (at Library/PackageCache/com.unity.barracuda@1.2.0-preview/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:1983)
Unity.Barracuda.ONNX.ONNXModelConverter.ConvertOnnxModel (Onnx.ModelProto onnxModel) (at Library/PackageCache/com.unity.barracuda@1.2.0-preview/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:1566)
Unity.Barracuda.ONNX.ONNXModelConverter.Convert (Google.Protobuf.CodedInputStream inputStream) (at Library/PackageCache/com.unity.barracuda@1.2.0-preview/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:89)
Unity.Barracuda.ONNX.ONNXModelConverter.Convert (System.String filePath) (at Library/PackageCache/com.unity.barracuda@1.2.0-preview/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:67)
Unity.Barracuda.ONNXModelImporter.OnImportAsset (UnityEditor.Experimental.AssetImporters.AssetImportContext ctx) (at Library/PackageCache/com.unity.barracuda@1.2.0-preview/Barracuda/Editor/ONNXModelImporter.cs:59)
UnityEditor.Experimental.AssetImporters.ScriptedImporter.GenerateAssetData (UnityEditor.Experimental.AssetImporters.AssetImportContext ctx) (at <208995a09fe148f5a6f6c571838c154f>:0)
UnityEditorInternal.InternalEditorUtility:ProjectWindowDrag(HierarchyProperty, Boolean)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
```


For newer versions, all I get is:

```
AssertionException: Assertion failure. Value was False
Expected: True
UnityEngine.Assertions.Assert.Fail (System.String message, System.String userMessage) (at <a1ac446df41c4a67becf2f8317dc1792>:0)
UnityEngine.Assertions.Assert.IsTrue (System.Boolean condition, System.String message) (at <a1ac446df41c4a67becf2f8317dc1792>:0)
UnityEngine.Assertions.Assert.IsTrue (System.Boolean condition) (at <a1ac446df41c4a67becf2f8317dc1792>:0)
Unity.Barracuda.ModelAnalyzer.ListTemporaryTensorShapes (Unity.Barracuda.Model model, System.Collections.Generic.IDictionary`2[TKey,TValue] inputShapes, System.Collections.Generic.IDictionary`2[System.String,System.Nullable`1[Unity.Barracuda.TensorShape]]& shapesByName) (at Library/PackageCache/com.unity.barracuda@1.3.1-preview/Barracuda/Runtime/Core/Backends/ModelAnalyzer.cs:389)
Unity.Barracuda.ModelAnalyzer.ListTemporaryTensorShapes (Unity.Barracuda.Model model, System.Collections.Generic.IDictionary`2[TKey,TValue] inputShapes) (at Library/PackageCache/com.unity.barracuda@1.3.1-preview/Barracuda/Runtime/Core/Backends/ModelAnalyzer.cs:70)
Unity.Barracuda.ModelAnalyzer.FindLargestNecessaryTensorShape (Unity.Barracuda.Model model, System.Collections.Generic.IDictionary`2[TKey,TValue] inputShapes) (at Library/PackageCache/com.unity.barracuda@1.3.1-preview/Barracuda/Runtime/Core/Backends/ModelAnalyzer.cs:670)
Unity.Barracuda.GenericVarsWithPreallocation.PrepareStorage (Unity.Barracuda.Model model, Unity.Barracuda.IOps ops, System.Collections.Generic.IDictionary`2[TKey,TValue] inputShapes) (at Library/PackageCache/com.unity.barracuda@1.3.1-preview/Barracuda/Runtime/Core/Backends/GenericWorker.cs:1353)
Unity.Barracuda.GenericWorker.PrepareForInput (System.Collections.Generic.IDictionary`2[TKey,TValue] inputShapes) (at Library/PackageCache/com.unity.barracuda@1.3.1-preview/Barracuda/Runtime/Core/Backends/GenericWorker.cs:116)
Unity.Barracuda.GenericWorker.SetInput (System.String name, Unity.Barracuda.Tensor x) (at Library/PackageCache/com.unity.barracuda@1.3.1-preview/Barracuda/Runtime/Core/Backends/GenericWorker.cs:130)
Unity.Barracuda.GenericWorker.Execute (System.Collections.Generic.IDictionary`2[TKey,TValue] inputs) (at Library/PackageCache/com.unity.barracuda@1.3.1-preview/Barracuda/Runtime/Core/Backends/GenericWorker.cs:145)
Unity.Barracuda.Compiler.Passes.IRShapeInferenceAndConstantFusing.FuseShapesIntoConstants (Unity.Barracuda.Model& model, System.Collections.Generic.IDictionary`2[TKey,TValue] shapesByName, System.Collections.Generic.IDictionary`2[TKey,TValue] ranksByName) (at Library/PackageCache/com.unity.barracuda@1.3.1-preview/Barracuda/Runtime/Core/Compiler/Passes/IRShapeInferenceAndConstantFusing.cs:117)
Unity.Barracuda.Compiler.Passes.IRShapeInferenceAndConstantFusing.Run (Unity.Barracuda.Model& model) (at Library/PackageCache/com.unity.barracuda@1.3.1-preview/Barracuda/Runtime/Core/Compiler/Passes/IRShapeInferenceAndConstantFusing.cs:23)
Unity.Barracuda.Compiler.Passes.IntermediateToRunnableNHWCPass.Run (Unity.Barracuda.Model& model) (at Library/PackageCache/com.unity.barracuda@1.3.1-preview/Barracuda/Runtime/Core/Compiler/Passes/IntermediateToRunnableNHWCPass.cs:12)
Unity.Barracuda.ONNX.ONNXModelConverter.Convert (Google.Protobuf.CodedInputStream inputStream) (at Library/PackageCache/com.unity.barracuda@1.3.1-preview/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:119)
Unity.Barracuda.ONNX.ONNXModelConverter.Convert (System.String filePath) (at Library/PackageCache/com.unity.barracuda@1.3.1-preview/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:83)
Unity.Barracuda.ONNXModelImporter.OnImportAsset (UnityEditor.Experimental.AssetImporters.AssetImportContext ctx) (at Library/PackageCache/com.unity.barracuda@1.3.1-preview/Barracuda/Editor/ONNXModelImporter.cs:58)
UnityEditor.Experimental.AssetImporters.ScriptedImporter.GenerateAssetData (UnityEditor.Experimental.AssetImporters.AssetImportContext ctx) (at <208995a09fe148f5a6f6c571838c154f>:0)
UnityEditorInternal.InternalEditorUtility:ProjectWindowDrag(HierarchyProperty, Boolean)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
```

This is on import of the model. Is there some part of the PyTorch implementation that is not supported?

**Comment by ArnoBen** [comment] 2021-03-09 21:23
@fmannhardt FIY, I used the same repo. I don't have more info since the project was not pursued on my end.

**Comment by AlexRibard** [comment] 2021-03-10 04:40
@ArnoBen and @fmannhardt sorry about that. That particular model got through the cracks.
I'll work on it, should be ok.
I only have the yolo-v3 version. Would it be possible to export me all through yolov5 as reference to see if the import?

**Comment by fmannhardt** [comment] 2021-03-10 07:32
@AlexRibard thanks for the quick response. Is there any workaround? The exception seems to indicate that this is something about non-fixed tensor dimensions `FindLargestNecessaryTensorShape `? Would changing this be helping until a fix is released?

For the YOLOv5 version (which seems to be not linked to any paper) the pre-trained ones you can download here:
https://github.com/ultralytics/yolov5/releases
https://github.com/ultralytics/yolov5/releases/download/v4.0/yolov5s.onnx

If it helps I can look at converting the different sizes for YOLOv3 to ONNX.

On YOLOv4, I think it uses a different operations and is not included in that repo but I haven't looked into it in detail.

**Comment by fmannhardt** [comment] 2021-03-10 11:35
I think I found a possible workaround. Their export script (both in https://github.com/ultralytics/yolov3 and https://github.com/ultralytics/yolov5) uses ONNX opset 12. If I specify opset 9 the 'tiny' variant loads without error. I yet have to test if it properly works though.

Here are the three YOLOv3 models:
https://www.dropbox.com/sh/id14h5ygu54504x/AADmLLAAVdtyHl0oZeqHiKCxa?dl=0
Actually the -spp and the standard one import but with a warning:

![afbeelding](https://user-images.githubusercontent.com/3202998/110623248-e0b87b80-819c-11eb-9b7e-7874cacfc2bf.png)

It is the `-tiny` variant that causes issues. I guess due to this conversion of the `constant_pad_nd` operation:
![afbeelding](https://user-images.githubusercontent.com/3202998/110623422-18bfbe80-819d-11eb-94e1-3ee848749e7e.png)

**Comment by fmannhardt** [comment] 2021-03-10 12:36
I have investigated further. Exporting to opset 9 means that I can import the YOLOv3-tiny model. However, this produces the following warning in the current PyTorch 1.8.0 and ONNY 1.8.1:

```
/anaconda/envs/xxx/lib/python3.8/site-packages/torch/onnx/symbolic_helper.py:346: UserWarning: You are trying to export the model with onnx:Upsample for ONNX opset version 9. This operator might cause results to not match the expected results by PyTorch.
ONNX's Upsample/Resize operator did not match Pytorch's Interpolation until opset 11. Attributes to determine how to transform the input were added in onnx:Resize in opset 11 to support Pytorch's behavior (like coordinate_transformation_mode and nearest_mode).
We recommend using opset 11 and above for models using this operator. 
```

Maybe this can be ignored, but I am not sure.

**Comment by AlexRibard** [comment] 2021-03-10 16:55
Yeah so the problem with the yolov3 is this part
![image](https://user-images.githubusercontent.com/12990800/110666192-178b9300-8197-11eb-98e3-909952df63e6.png)
Our code breaks in the constant fusing atm.
So if you want a work around, you can edit the onnx to modify that Pad layer to have fixed pads.
That warning should be ok. There was some discrepancy between Pytorch and onnx upsample code in opset 9 but it should be ok when running in Barracuda.
I've got the fix for the initial yolov3 model. I'll push it and checkout the other models you provided.

**Comment by AlexRibard** [comment] 2021-03-19 20:01
Hey guys!
Wanted to tell you that I've pushed a fixed for all those models in 1.3.3 (yolovs_spp, yolov3, yolov5s)
(yolov3_tiny has some import issues that will not make it in 13.3 unfortunately).

I'm keeping the ticket opened as I did notice some precision issues when running models. Currently only valid against reference at 10^-2 relative error (10^-5 absolute).
Give the output range I think it's ok-ish. But I'll let you guys be the judge for that :)

Let me know

**Comment by fmannhardt** [comment] 2021-03-19 20:09
Thank you for the quick fix, I hope to be able to retry next week.

**Comment by fmannhardt** [comment] 2021-05-06 09:15
I can confirm that we got a YOLOv3 Tiny variant running when making sure that all the parameters e.g. to certain Slice layers were made constant. Maybe for other encountering similar issues. Have a look at ONNX Simplifier (https://github.com/daquexian/onnx-simplifier) which can remove unnecessary non-constant values. It will also remove the part that I showed above.

**Comment by FlorentGuinier** [comment] 2021-05-06 09:20
Awesome, thanks for feedback!

**Closed as completed by FlorentGuinier** 2021-05-06 09:20 UTC

**Comment by Ademord** [comment] 2021-06-07 15:44
> I can confirm that we got a YOLOv3 Tiny variant running when making sure that all the parameters e.g. to certain Slice layers were made constant. Maybe for other encountering similar issues. Have a look at ONNX Simplifier (https://github.com/daquexian/onnx-simplifier) which can remove unnecessary non-constant values. It will also remove the part that I showed above.

could you share the v3 and v5 models that you got working please?

**Comment by Ademord** [comment] 2021-06-07 15:44
> I can confirm that we got a YOLOv3 Tiny variant running when making sure that all the parameters e.g. to certain Slice layers were made constant. Maybe for other encountering similar issues. Have a look at ONNX Simplifier (https://github.com/daquexian/onnx-simplifier) which can remove unnecessary non-constant values. It will also remove the part that I showed above.

could you share the v3 and v5 models that you got working please? @fmannhardt

**Comment by ntxucb** [comment] 2021-12-25 04:00
> 

do you mind telling what tool did you used to plot your network?

**Comment by ArnoBen** [comment] 2021-12-25 09:35
@ntxucb It's Netron : https://netron.app/
