### ISSUE TITLE
OnnxImportException: Unexpected error while parsing layer 29 of type Slice. Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by chinmaychinara91** [Unity-Technologies/barracuda-release#95] opened 2020-10-15 21:01 UTC
Hello Baracuda Team,

I am trying to import an LSTM based classification network into Unity.  

Barracuda version: 1.1.2 (preview)
Pytorch: 1.3
Opset Version: 9

This is my stack trace:

Asset import failed, "Assets/Resources/Models/crnn_decoder.onnx" > OnnxImportException: Unexpected error while parsing layer 29 of type Slice.
Index was outside the bounds of the array.

Json: { "input": [ "LSTM.weight_ih_l0" ], "output": [ "29" ], "opType": "Slice", "attribute": [ { "name": "axes", "ints": [ "0" ], "type": "INTS" }, { "name": "ends", "ints": [ "512" ], "type": "INTS" }, { "name": "starts", "ints": [ "0" ], "type": "INTS" } ] }
  at Unity.Barracuda.TensorShape..ctor (System.Int32[] shape) [0x00000] in C:\Users\chinm\Desktop\MSELI_Simulation\Library\PackageCache\com.unity.barracuda@1.1.2-preview\Barracuda\Runtime\Core\Tensor.cs:132 
  at Unity.Barracuda.Tensor..ctor (System.Int32[] shape, System.String name) [0x00000] in C:\Users\chinm\Desktop\MSELI_Simulation\Library\PackageCache\com.unity.barracuda@1.1.2-preview\Barracuda\Runtime\Core\Tensor.cs:891 
  at Unity.Barracuda.ONNX.ONNXTensor.Slice (System.Int32[] starts, System.Int32[] ends, System.Int32[] steps) [0x000d4] in C:\Users\chinm\Desktop\MSELI_Simulation\Library\PackageCache\com.unity.barracuda@1.1.2-preview\Barracuda\Runtime\ONNX\ONNXTensor.cs:267 
  at Unity.Barracuda.ONNX.ONNXModelConverter+<>c__DisplayClass15_0.<.ctor>b__8 (Unity.Barracuda.ModelBuilder net, Unity.Barracuda.ONNX.ONNXNodeWrapper node) [0x001c9] in C:\Users\chinm\Desktop\MSELI_Simulation\Library\PackageCache\com.unity.barracuda@1.1.2-preview\Barracuda\Runtime\ONNX\ONNXModelConverter.cs:341 
  at Unity.Barracuda.ONNX.ONNXModelConverter.ConvertOnnxModel (Onnx.ModelProto onnxModel) [0x0036e] in C:\Users\chinm\Desktop\MSELI_Simulation\Library\PackageCache\com.unity.barracuda@1.1.2-preview\Barracuda\Runtime\ONNX\ONNXModelConverter.cs:1210 

Unity.Barracuda.ONNX.ONNXModelConverter.Err (Unity.Barracuda.Model model, System.String layerName, System.String message, System.String extendedMessage, System.String debugMessage) (at Library/PackageCache/com.unity.barracuda@1.1.2-preview/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:1511)
Unity.Barracuda.ONNX.ONNXModelConverter.ConvertOnnxModel (Onnx.ModelProto onnxModel) (at Library/PackageCache/com.unity.barracuda@1.1.2-preview/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:1219)
Unity.Barracuda.ONNX.ONNXModelConverter.Convert (Google.Protobuf.CodedInputStream inputStream) (at Library/PackageCache/com.unity.barracuda@1.1.2-preview/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:82)
Unity.Barracuda.ONNX.ONNXModelConverter.Convert (System.String filePath) (at Library/PackageCache/com.unity.barracuda@1.1.2-preview/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:60)
Unity.Barracuda.ONNXModelImporter.OnImportAsset (UnityEditor.Experimental.AssetImporters.AssetImportContext ctx) (at Library/PackageCache/com.unity.barracuda@1.1.2-preview/Barracuda/Editor/ONNXModelImporter.cs:44)
UnityEditor.Experimental.AssetImporters.ScriptedImporter.GenerateAssetData (UnityEditor.Experimental.AssetImporters.AssetImportContext ctx) (at <90d4bcb003fb405fb09241aed2f178aa>:0)
UnityEditor.Experimental.AssetImporters.AssetImporterEditor:ApplyRevertGUI()
Unity.Barracuda.ONNXModelImporterEditor:OnInspectorGUI() (at Library/PackageCache/com.unity.barracuda@1.1.2-preview/Barracuda/Editor/ONNXModelImporterEditor.cs:41)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

UnityEditor.Experimental.AssetImporters.AssetImporterEditor:ApplyRevertGUI()
Unity.Barracuda.ONNXModelImporterEditor:OnInspectorGUI() (at Library/PackageCache/com.unity.barracuda@1.1.2-preview/Barracuda/Editor/ONNXModelImporterEditor.cs:41)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

What kind of error is this it just says unexpected error with index out of bounds. This network works perfectly ok in Pytorch.
The onnx is attached.
[crnn_decoder.zip](https://github.com/Unity-Technologies/barracuda-release/files/5387789/crnn_decoder.zip)

@andrewfengusa

**Comment by chinmaychinara91** [comment] 2020-10-15 21:11
> Hello Baracuda Team,
> 
> I am trying to import an LSTM based classification network into Unity.
> 
> Barracuda version: 1.1.2 (preview)
> Pytorch: 1.3
> Opset Version: 9
> 
> This is my stack trace:
> 
> Asset import failed, "Assets/Resources/Models/crnn_decoder.onnx" > OnnxImportException: Unexpected error while parsing layer 29 of type Slice.
> Index was outside the bounds of the array.
> 
> Json: { "input": [ "LSTM.weight_ih_l0" ], "output": [ "29" ], "opType": "Slice", "attribute": [ { "name": "axes", "ints": [ "0" ], "type": "INTS" }, { "name": "ends", "ints": [ "512" ], "type": "INTS" }, { "name": "starts", "ints": [ "0" ], "type": "INTS" } ] }
> at Unity.Barracuda.TensorShape..ctor (System.Int32[] shape) [0x00000] in C:\Users\chinm\Desktop\MSELI_Simulation\Library\PackageCache\[com.unity.barracuda@1.1.2-preview](mailto:com.unity.barracuda@1.1.2-preview)\Barracuda\Runtime\Core\Tensor.cs:132
> at Unity.Barracuda.Tensor..ctor (System.Int32[] shape, System.String name) [0x00000] in C:\Users\chinm\Desktop\MSELI_Simulation\Library\PackageCache\[com.unity.barracuda@1.1.2-preview](mailto:com.unity.barracuda@1.1.2-preview)\Barracuda\Runtime\Core\Tensor.cs:891
> at Unity.Barracuda.ONNX.ONNXTensor.Slice (System.Int32[] starts, System.Int32[] ends, System.Int32[] steps) [0x000d4] in C:\Users\chinm\Desktop\MSELI_Simulation\Library\PackageCache\[com.unity.barracuda@1.1.2-preview](mailto:com.unity.barracuda@1.1.2-preview)\Barracuda\Runtime\ONNX\ONNXTensor.cs:267
> at Unity.Barracuda.ONNX.ONNXModelConverter+<>c__DisplayClass15_0.<.ctor>b__8 (Unity.Barracuda.ModelBuilder net, Unity.Barracuda.ONNX.ONNXNodeWrapper node) [0x001c9] in C:\Users\chinm\Desktop\MSELI_Simulation\Library\PackageCache\[com.unity.barracuda@1.1.2-preview](mailto:com.unity.barracuda@1.1.2-preview)\Barracuda\Runtime\ONNX\ONNXModelConverter.cs:341
> at Unity.Barracuda.ONNX.ONNXModelConverter.ConvertOnnxModel (Onnx.ModelProto onnxModel) [0x0036e] in C:\Users\chinm\Desktop\MSELI_Simulation\Library\PackageCache\[com.unity.barracuda@1.1.2-preview](mailto:com.unity.barracuda@1.1.2-preview)\Barracuda\Runtime\ONNX\ONNXModelConverter.cs:1210
> 
> Unity.Barracuda.ONNX.ONNXModelConverter.Err (Unity.Barracuda.Model model, System.String layerName, System.String message, System.String extendedMessage, System.String debugMessage) (at Library/PackageCache/com.unity.barracuda@1.1.2-preview/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:1511)
> Unity.Barracuda.ONNX.ONNXModelConverter.ConvertOnnxModel (Onnx.ModelProto onnxModel) (at Library/PackageCache/com.unity.barracuda@1.1.2-preview/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:1219)
> Unity.Barracuda.ONNX.ONNXModelConverter.Convert (Google.Protobuf.CodedInputStream inputStream) (at Library/PackageCache/com.unity.barracuda@1.1.2-preview/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:82)
> Unity.Barracuda.ONNX.ONNXModelConverter.Convert (System.String filePath) (at Library/PackageCache/com.unity.barracuda@1.1.2-preview/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:60)
> Unity.Barracuda.ONNXModelImporter.OnImportAsset (UnityEditor.Experimental.AssetImporters.AssetImportContext ctx) (at Library/PackageCache/com.unity.barracuda@1.1.2-preview/Barracuda/Editor/ONNXModelImporter.cs:44)
> UnityEditor.Experimental.AssetImporters.ScriptedImporter.GenerateAssetData (UnityEditor.Experimental.AssetImporters.AssetImportContext ctx) (at <90d4bcb003fb405fb09241aed2f178aa>:0)
> UnityEditor.Experimental.AssetImporters.AssetImporterEditor:ApplyRevertGUI()
> Unity.Barracuda.ONNXModelImporterEditor:OnInspectorGUI() (at Library/PackageCache/com.unity.barracuda@1.1.2-preview/Barracuda/Editor/ONNXModelImporterEditor.cs:41)
> UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
> 
> UnityEditor.Experimental.AssetImporters.AssetImporterEditor:ApplyRevertGUI()
> Unity.Barracuda.ONNXModelImporterEditor:OnInspectorGUI() (at Library/PackageCache/com.unity.barracuda@1.1.2-preview/Barracuda/Editor/ONNXModelImporterEditor.cs:41)
> UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
> 
> What kind of error is this it just says unexpected error with index out of bounds. This network works perfectly ok in Pytorch.
> The onnx is attached.
> [crnn_decoder.zip](https://github.com/Unity-Technologies/barracuda-release/files/5387789/crnn_decoder.zip)

**Comment by AlexRibard** [comment] 2020-10-15 21:33
Hi! Thanks for including the model. We will take a look at it.
It is most likely a importer error on our end

**Comment by chinmaychinara91** [comment] 2020-10-15 21:40
> Hi! Thanks for including the model. We will take a look at it.
> It is most likely a importer error on our end

Thanks for the quick response @AlexRibard. Hope a solution is found.

**Comment by chinmaychinara91** [comment] 2020-10-19 19:04
@AlexRibard were you able to figure out what kind of import issue this could be and a way around it ?

**Comment by AlexRibard** [comment] 2020-10-20 17:02
Yes, we are miss-interpreting the rank coming out of the LSTM node. Fixing the issue

**Comment by AlexRibard** [comment] 2020-10-20 18:43
Hi! I took a look at it. The issue is a bit more sever than I though. Looks like we don't support fully generic LSTM node.
Adding it to the TODO.

**Comment by chinmaychinara91** [comment] 2020-10-20 20:27
@AlexRibard so is there something that can be done to tackle this issue temporarily as this is the crux of my classification logic. Can you share in details why this index out of bounds error for a layer that does simple Slicing?

**Comment by AlexRibard** [comment] 2020-10-20 21:32
The main problem is on our end and coming upstream from the LSTM node.
Let's follow up via email. I managed to get your model running, but have some computation errors.
You can reach me at alxandre.ribard @ unity3d.com
Main question for you? Are you exporting from TF or Keras?

**Comment by chinmaychinara91** [comment] 2020-10-20 21:52
I just sent you an email. Let's take it from there.

**Comment by amirebrahimi** [comment] 2021-03-22 17:56
This work on LSTM is now complete and will be included in v1.3.3.

**Closed as completed by amirebrahimi** 2021-03-22 17:56 UTC

**Comment by chinmaychinara91** [comment] 2022-03-12 02:40
Hello,

I am trying to import an LSTM based classification network into Unity. This is the same model which is mentioned at the beginning of this post.

Barracuda version: 2.0
Pytorch: 1.3
Opset Version: 9

I see this in the output shape:
![Capture](https://user-images.githubusercontent.com/21283733/158000582-7b7581cf-1285-4d35-8086-3436f74b1f4a.PNG)

Why is the output shape unknown here ?

The onnx:
[Uploading crnn_lstm_decoder.zip…]()
