### ISSUE TITLE
LSTM Execution in Unity

### ISSUE THREAD

**Issue by giorgiogamba** [Unity-Technologies/barracuda-release#260] opened 2022-02-14 11:06 UTC
Hi,
I'm building an application that wants to make inference using a neural network through Barracuda.
I've got a LSTM network with 3 layers and 50 nodes for layer and in ONNX format and a script that simply manages the input tensor creation and inference execution.
The problem is that, when the inference is executed, the application lags and freezes a bit, creating a jerky rendering.
Am I doing something wrong, or maybe I'm doing something wrong in the setup?
Thank you in advance!

**Comment by FlorentGuinier** [comment] 2022-02-14 11:22
Hi @giorgiogamba,

I would advice looking at the [Unity profiler](https://docs.unity3d.com/Manual/Profiler.html) to understand the behavior. Please however note that we [do not currently support LSTM outside of the ML-Agent](https://docs.unity3d.com/Packages/com.unity.barracuda@2.4/manual/SupportedOperators.html?q=LSTM#LSTM) context thus you might be hitting a slow path explaining the lag.

I'm closing the issue as LSTM outside of ML-Agent are not supported at the moment (thus we don't garanty performance for them), feel free to reopen if you think the problem is elsewhere.

Thanks,
Florent

**Closed as completed by FlorentGuinier** 2022-02-14 11:22 UTC
